version: '3'
services:
  app:
    build: .
    command: gunicorn main:server
    volumes:
      - /home/ubuntu/docker/covid-19/data:/var/jenkins_home/workspace/Covid-19/data
    ports:
      - "8050:8050"