version: '3'
services:
  app:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 main:server
    volumes:
      - /home/ubuntu/docker/covid-19/data:/var/jenkins_home/workspace/Covid-19/data
    ports:
      - "8000:8000"